#!/bin/sh
# live-build configuration for the Sysible Linux ISO.
set -e
lb config noauto \
  --distribution bookworm \
  --archive-areas "main contrib non-free non-free-firmware" \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --debian-installer none \
  --bootappend-live "boot=live components username=sysible" \
  --iso-application "Sysible Linux" \
  --iso-publisher "Sysible" \
  --iso-volume "Sysible Linux" \
  --memtest none \
  "${@}"
