#!/bin/sh
# live-build configuration for the Sysible Linux ISO.
set -e
lb config noauto \
  --distribution "${SYSIBLE_CODENAME:-bookworm}" \
  --archive-areas "main contrib non-free non-free-firmware" \
  --architectures amd64 \
  --binary-images iso-hybrid \
  --debian-installer none \
  --bootappend-live "boot=live components username=sysible user-fullname=Sysible user-default-groups=sudo,kvm,libvirt,docker,wireshark,plugdev,netdev,video,audio" \
  --iso-application "Sysible Linux" \
  --iso-publisher "Sysible" \
  --iso-volume "Sysible Linux" \
  --memtest none \
  "${@}"
